---
- hosts: "{{ hostname }}"
  gather_facts: no
  tasks:
    - name: Uninstall package via zypper
      community.general.zypper:
        name: "{{ names }}"
        state: removed
        update_cache: true
      register: packages
    - name: Reboot
      ansible.builtin.reboot:
        post_reboot_delay: 60
      when: packages is changed
